In [1]:
import pandas as pd
import numpy as np

In [2]:
canada = pd.read_csv('CANADA.csv', encoding='latin-1')#,delimiter = '\t', quoting = 3, encoding='utf-8')
canada.head()

Place Name   Latitude   Longitude
0           Yorkton, SK, Canada  51.213890 -102.462776
1            Warman, SK, Canada  52.321945 -106.584167
2     Swift Current, SK, Canada  50.288055 -107.793892
3  North Battleford, SK, Canada  52.757500 -108.286110
4         Moose Jaw, SK, Canada  50.393333 -105.551941

In [3]:
target = []
for i in range(len(canada)):
    target.append(1)

In [4]:
print(len(canada))
print(len(target))

352
352


In [5]:
canada['target'] = target
canada.head()

Place Name   Latitude   Longitude  target
0           Yorkton, SK, Canada  51.213890 -102.462776       1
1            Warman, SK, Canada  52.321945 -106.584167       1
2     Swift Current, SK, Canada  50.288055 -107.793892       1
3  North Battleford, SK, Canada  52.757500 -108.286110       1
4         Moose Jaw, SK, Canada  50.393333 -105.551941       1

In [6]:
canada.drop(['Place Name'],axis = 1, inplace =True)

In [7]:
canada.head()

Latitude   Longitude  target
0  51.213890 -102.462776       1
1  52.321945 -106.584167       1
2  50.288055 -107.793892       1
3  52.757500 -108.286110       1
4  50.393333 -105.551941       1

In [8]:
usa = pd.read_csv('USA.csv', encoding='latin-1')#, delimiter = '\t', quoting = 3, encoding='utf-8')
usa.head()


Place Name   Latitude   Longitude
0  Port Hueneme, CA, the US  34.155834 -119.202789
1           Auburn, NY, USA  42.933334  -76.566666
2     Jamestown, NY, the US  42.095554  -79.238609
3           Fulton, MO, USA  38.846668  -91.948059
4       Bedford, OH, the US  41.392502  -81.534447

In [9]:
targ = []
for i in range(len(usa)):
    targ.append(0)

In [10]:
usa['target'] = targ
usa.head()

Place Name   Latitude   Longitude  target
0  Port Hueneme, CA, the US  34.155834 -119.202789       0
1           Auburn, NY, USA  42.933334  -76.566666       0
2     Jamestown, NY, the US  42.095554  -79.238609       0
3           Fulton, MO, USA  38.846668  -91.948059       0
4       Bedford, OH, the US  41.392502  -81.534447       0

In [11]:
print(len(usa))

400


In [12]:
usa.drop(['Place Name'],axis = 1, inplace =True)


In [13]:
usa.head()

Latitude   Longitude  target
0  34.155834 -119.202789       0
1  42.933334  -76.566666       0
2  42.095554  -79.238609       0
3  38.846668  -91.948059       0
4  41.392502  -81.534447       0

In [14]:
usa.tail(30)

Latitude   Longitude  target
370  38.297539 -122.286865       0
371  41.027054  -73.620071       0
372  33.014568  -97.096954       0
373  33.019844  -96.698883       0
374  33.753746  -84.386330       0
375  33.952602  -84.549934       0
376  36.865601  -87.488617       0
377  34.170563 -118.837593       0
378  41.257160  -95.995102       0
379  37.529659 -122.040237       0
380  32.799576  -97.269180       0
381  40.855930  -73.200668       0
382  34.180840 -118.308968       0
383  43.801357  -91.239578       0
384  43.061615  -88.107948       0
385  38.600807 -121.377037       0
386  47.570656 -122.222069       0
387  38.244923 -122.626991       0
388  37.238754  -76.509674       0
389  39.633068 -106.522217       0
390  26.103039  -80.401382       0
391  38.108086 -122.575150       0
392  44.049999  -91.633331       0
393  47.307323 -122.228455       0
394  40.666893 -111.887993       0
395  40.391617 -111.850769       0
396  34.190163 -118.131317       0
397  36.825230 -119.702919       0
398  34.933060 -114.588852       0
399  39.250664  -76.520515       0

In [15]:
# Taking out data for testing.
test_ca = canada.iloc[-30:] # last 30
test_usa = usa.iloc[-30:]

In [16]:
test_ca = test_ca.values 
test_usa = test_usa.values

In [17]:
# for some weird reason, pd.concat() was not concatenating properly so I had to convert to numpy, concat, then convert back to
# pandas

In [18]:
#test_ca.reset_index(drop=True,inplace=True)
#test_usa.reset_index(drop=True,inplace=True)

In [19]:
#test_ca.head()

In [20]:
#test_usa.head()

In [21]:
test_data = np.concatenate([test_ca, test_usa])

In [22]:
test_data[:5]

array([[  49.095001, -117.709999,    1.      ],
       [  43.683334,  -79.76667 ,    1.      ],
       [  53.631611, -113.323975,    1.      ],
       [  43.255203,  -79.843826,    1.      ],
       [  42.317432,  -83.026772,    1.      ]])

In [23]:
test_data = pd.DataFrame(test_data, columns=['Latitude','Longitude','target'])

In [24]:
test_data.head()

Latitude   Longitude  target
0  49.095001 -117.709999     1.0
1  43.683334  -79.766670     1.0
2  53.631611 -113.323975     1.0
3  43.255203  -79.843826     1.0
4  42.317432  -83.026772     1.0

In [25]:
train_ca = canada.iloc[:322]
train_usa = usa.iloc[:370]

In [26]:
train_ca = train_ca.values
train_usa = train_usa.values

In [27]:
#train_ca.reset_index(drop=True,inplace=True)
#train_usa.reset_index(drop=True,inplace=True)

In [28]:
#train_ca.head()

In [29]:
#train_usa.head()

In [30]:
train_data = np.concatenate([train_ca, train_usa])

In [31]:
train_data

array([[  51.21389 , -102.462776,    1.      ],
       [  52.321945, -106.584167,    1.      ],
       [  50.288055, -107.793892,    1.      ],
       ...,
       [  37.494656, -120.846596,    0.      ],
       [  31.231293,  -84.210464,    0.      ],
       [  35.198284, -111.651299,    0.      ]])

In [32]:
train_data = pd.DataFrame(train_data, columns=['Latitude','Longitude','target'])

In [33]:
train_data.head()

Latitude   Longitude  target
0  51.213890 -102.462776     1.0
1  52.321945 -106.584167     1.0
2  50.288055 -107.793892     1.0
3  52.757500 -108.286110     1.0
4  50.393333 -105.551941     1.0

In [34]:
test_data['target'].unique()

array([1., 0.])

In [35]:
train_data['target'].unique()

array([1., 0.])

In [36]:
train_data = train_data.sample(frac=1).reset_index(drop=True) # Shuffling the data

In [37]:
train_data.head()

Latitude   Longitude  target
0  33.983070 -118.096733     0.0
1  45.319649  -72.648338     1.0
2  37.036064  -95.620537     0.0
3  45.900002  -71.349998     1.0
4  46.849998  -71.733330     1.0

In [38]:
x = train_data.iloc[:, 0:2]
y = train_data.iloc[:, 2]

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 0)

In [40]:
from sklearn.naive_bayes import GaussianNB
classifier= GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [41]:
y_pred = classifier.predict(x_test)

In [42]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)

In [43]:
cm

array([[76,  7],
       [ 3, 87]], dtype=int64)

In [44]:
print(accuracy_score(y_pred, y_test))

0.9421965317919075


In [45]:
re_x = test_data.iloc[:, 0:2]
re_y = test_data.iloc[:, 2]

In [46]:
y_predR = classifier.predict(re_x)

In [47]:
print(accuracy_score(y_predR, re_y))

0.8833333333333333


In [48]:
from sklearn.metrics import roc_auc_score

In [49]:
# Predict class probabilities
y_pred_2 = classifier.predict_proba(re_x)
 
# Keep only the positive class
y_pred_2 = [y[1] for y in y_pred_2]

In [50]:
print(roc_auc_score(re_y, y_pred_2))

0.9655555555555556


In [ ]:
# Oh wowww